const PRODUCTS={
 sweet:{name:'황금한입 고구마칩',unit:'박스',meta:'01 · FOOD',desc:'달콤하고 바삭한 고구마 스낵',main:'assets/sweet-main.webp',images:['assets/sweet-main.webp']},
 dryer:{name:'HANBUL 헤어드라이어',unit:'개',meta:'02 · APPLIANCE',desc:'깔끔한 화이트 바디의 생활가전',main:'assets/dryer-main.webp',images:['assets/dryer-main.webp']},
 sesame:{name:'오모나 참깨강정',unit:'박스',meta:'03 · FOOD',desc:'고소하고 바삭한 참깨 전통 간식',main:'assets/sesame-main.webp',images:['assets/sesame-main.webp']}
};
let cart={sweet:0,dryer:0,sesame:0}; let activeDetail='sweet';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function total(){return Object.values(cart).reduce((a,b)=>a+b,0)}
function renderProducts(){document.getElementById('productList').innerHTML=Object.entries(PRODUCTS).map(([id,p])=>`<article class="product" data-id="${id}"><div class="product-img"><img src="${p.main}" alt="${esc(p.name)}"><button class="view-detail" data-open-detail="${id}">사진 보기</button></div><div><div class="product-meta">${p.meta}</div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p></div><div class="qty-wrap"><span class="qty-label">주문수량 · ${p.unit}</span><div class="qty"><button type="button" data-minus="${id}" aria-label="${esc(p.name)} 수량 감소">−</button><input data-qty="${id}" type="number" min="0" inputmode="numeric" value="${cart[id]}" aria-label="${esc(p.name)} 주문 수량"><button type="button" data-plus="${id}" aria-label="${esc(p.name)} 수량 증가">+</button></div><span class="line-total">선택 <b>${cart[id]}${p.unit}</b></span></div></article>`).join(''); bindProductEvents()}
function renderSummary(){const chosen=Object.entries(cart).filter(([,q])=>q>0);document.querySelectorAll('[data-count]').forEach(el=>el.textContent=total());document.getElementById('summaryItems').innerHTML=chosen.length?chosen.map(([id,q])=>`<div class="summary-row"><span>${esc(PRODUCTS[id].name)}</span><b>${q}${PRODUCTS[id].unit}</b></div>`).join(''):'<div class="summary-empty">선택한 상품이 없습니다.</div>';document.getElementById('goInfo').disabled=!chosen.length;document.getElementById('mobileSummary').textContent=chosen.length?`${chosen.length}개 품목 선택`:'상품을 선택하세요'}
function updateCart(id,q){cart[id]=Math.max(0,Number(q)||0);renderProducts();renderSummary()}
function bindProductEvents(){document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>updateCart(b.dataset.minus,cart[b.dataset.minus]-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>updateCart(b.dataset.plus,cart[b.dataset.plus]+1));document.querySelectorAll('[data-qty]').forEach(i=>i.oninput=()=>{cart[i.dataset.qty]=Math.max(0,Number(i.value)||0);renderSummary();const line=i.closest('.product').querySelector('.line-total b');line.textContent=`${cart[i.dataset.qty]}${PRODUCTS[i.dataset.qty].unit}`});document.querySelectorAll('[data-open-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();openDetail(b.dataset.openDetail)})}
function openDetail(id){activeDetail=id;const p=PRODUCTS[id];document.getElementById('detailTitle').textContent=p.meta;document.getElementById('detailName').textContent=p.name;document.getElementById('detailDesc').textContent=p.desc;document.getElementById('detailImages').innerHTML=p.images.map((src,i)=>`<img src="${src}" alt="${esc(p.name)} 이미지 ${i+1}">`).join('');document.getElementById('detail').classList.add('open');document.body.classList.add('lock')}
function closeDetail(){document.getElementById('detail').classList.remove('open');document.body.classList.remove('lock')}
document.getElementById('detailClose').onclick=closeDetail;document.getElementById('detail').onclick=e=>{if(e.target.id==='detail')closeDetail()};document.getElementById('detailAdd').onclick=()=>{updateCart(activeDetail,cart[activeDetail]+1);closeDetail();document.getElementById('order').scrollIntoView({behavior:'smooth'})};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
function jumpInfo(){if(!total())return;document.getElementById('info').scrollIntoView({behavior:'smooth'})}document.getElementById('goInfo').onclick=jumpInfo;document.getElementById('topCart').onclick=()=>total()?jumpInfo():document.getElementById('order').scrollIntoView({behavior:'smooth'});document.getElementById('mobileCart').onclick=()=>total()?jumpInfo():document.getElementById('order').scrollIntoView({behavior:'smooth'});
function values(){return{company:document.getElementById('company').value.trim(),contact:document.getElementById('contact').value.trim(),phone:document.getElementById('phone').value.trim(),email:document.getElementById('email').value.trim(),address:document.getElementById('address').value.trim(),deliveryDate:document.getElementById('deliveryDate').value,channel:document.getElementById('channel').value,memo:document.getElementById('memo').value.trim()}}
function validate(){const v=values();if(!total()){alert('주문할 상품 수량을 먼저 선택하세요.');document.getElementById('order').scrollIntoView();return null}if(!v.company||!v.contact||!v.phone||!v.address){alert('회사명, 담당자, 연락처, 배송지는 필수입니다.');return null}if(!document.getElementById('agree').checked){alert('검수용 화면 확인 체크가 필요합니다.');return null}return v}
function review(v){const chosen=Object.entries(cart).filter(([,q])=>q>0);document.getElementById('reviewList').innerHTML=`<div class="review-line"><strong>주문 상품</strong><div class="review-products">${chosen.map(([id,q])=>`<div class="review-product"><span>${esc(PRODUCTS[id].name)}</span><b>${q}${PRODUCTS[id].unit}</b></div>`).join('')}</div></div><div class="review-line"><strong>거래처</strong><span>${esc(v.company)} · ${esc(v.contact)} · ${esc(v.phone)}</span></div><div class="review-line"><strong>배송지</strong><span>${esc(v.address)}</span></div><div class="review-line"><strong>희망 납품일</strong><span>${esc(v.deliveryDate||'미지정')}</span></div><div class="review-line"><strong>주문 경로</strong><span>${esc(v.channel)}</span></div><div class="review-line"><strong>요청사항</strong><span>${esc(v.memo||'없음')}</span></div>`;document.getElementById('review').classList.remove('hide');document.getElementById('reviewCard').classList.remove('hide');document.getElementById('successCard').classList.add('hide');document.getElementById('review').scrollIntoView({behavior:'smooth'})}
document.getElementById('goReview').onclick=()=>{const v=validate();if(v)review(v)};document.getElementById('backInfo').onclick=()=>document.getElementById('info').scrollIntoView({behavior:'smooth'});
function code(){const d=new Date();const y=String(d.getFullYear()).slice(-2),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `M9-${y}${m}${day}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
document.getElementById('submitOrder').onclick=()=>{const v=validate();if(!v)return;const order={code:code(),created:new Date().toISOString(),status:'received',cart:{...cart},...v};const list=JSON.parse(localStorage.getItem('m9-order-demo')||'[]');list.unshift(order);localStorage.setItem('m9-order-demo',JSON.stringify(list));document.getElementById('orderCode').textContent=order.code;document.getElementById('reviewCard').classList.add('hide');document.getElementById('successCard').classList.remove('hide');document.getElementById('review').scrollIntoView({behavior:'smooth'});};
document.getElementById('newOrder').onclick=()=>{cart={sweet:0,dryer:0,sesame:0};['company','contact','phone','email','address','memo','deliveryDate'].forEach(id=>document.getElementById(id).value='');document.getElementById('agree').checked=false;document.getElementById('review').classList.add('hide');renderProducts();renderSummary();document.getElementById('order').scrollIntoView({behavior:'smooth'})};
renderProducts();renderSummary();